changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "🔧 Maintenance"
      labels:
        - "maintenance"
    - title: "📚 Documentation"
      labels:
        - "documentation"
    - title: "🚨 Breaking Changes"
      labels:
        - "breaking"
    - title: "🧹 Chore"
      labels:
        - "chore"
    - title: "🚩 Other"
      labels:
        - "other"
    - title: "🚦 CI/CD"
      labels:
        - "ci/cd"
    - title: "🔍 Tests"
      labels:
        - "test"
