name: .NET Pack and Publish Tool

on: 
  push:
    tags:
      - v*

jobs:
  publish_nuget_package:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'
        
      - name: Package NuGet package
        run: dotnet pack -c Release -o nupkg
        
      - name: Publish NuGet package
        env:
          API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push ./nupkg/*.nupkg --api-key $API_KEY --source 'https://api.nuget.org/v3/index.json'